-- ============================================================
-- Supabase SQL Editor에서 실행하세요
-- ============================================================

-- ===== BEAUTY =====

-- MST_SUPPLIER → beauty_mst_supplier
DROP TABLE IF EXISTS "beauty_mst_supplier" CASCADE;
CREATE TABLE "beauty_mst_supplier" (
  "SUPPLIER_ID" TEXT,
  "SUPPLIER_NAME" TEXT,
  "SUPPLIER_TYPE" TEXT,
  "COUNTRY" TEXT,
  "LEAD_TIME_DAYS" TEXT,
  "MOQ" BIGINT,
  "PAYMENT_TERMS" TEXT
  , PRIMARY KEY ("SUPPLIER_ID")
);
ALTER TABLE "beauty_mst_supplier" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_supplier" FOR ALL USING (true) WITH CHECK (true);


-- MST_CHANNEL → beauty_mst_channel
DROP TABLE IF EXISTS "beauty_mst_channel" CASCADE;
CREATE TABLE "beauty_mst_channel" (
  "CHANNEL_ID" TEXT,
  "CHANNEL_NAME" TEXT,
  "CHANNEL_TYPE" TEXT,
  "REGION" TEXT,
  "CURRENCY" TEXT,
  "PLATFORM_FEE_PCT" BIGINT,
  "LOCATION" TEXT
  , PRIMARY KEY ("CHANNEL_ID")
);
ALTER TABLE "beauty_mst_channel" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_channel" FOR ALL USING (true) WITH CHECK (true);


-- MST_PRODUCT → beauty_mst_product
DROP TABLE IF EXISTS "beauty_mst_product" CASCADE;
CREATE TABLE "beauty_mst_product" (
  "PRODUCT_ID" TEXT,
  "PRODUCT_NAME" TEXT,
  "CATEGORY" TEXT,
  "DEMAND_TYPE" TEXT,
  "SEASONAL_PEAK" TEXT,
  "LIFECYCLE_STAGE" TEXT,
  "SUPPLIER_ID" TEXT,
  "PRICE_KRW" BIGINT,
  "PRICE_USD" DOUBLE PRECISION,
  "LAUNCH_DATE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("PRODUCT_ID")
);
ALTER TABLE "beauty_mst_product" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_product" FOR ALL USING (true) WITH CHECK (true);


-- MST_LOCATION → beauty_mst_location
DROP TABLE IF EXISTS "beauty_mst_location" CASCADE;
CREATE TABLE "beauty_mst_location" (
  "LOCATION_ID" TEXT,
  "LOCATION_NAME" TEXT,
  "LOCATION_TYPE" TEXT,
  "REGION" TEXT
  , PRIMARY KEY ("LOCATION_ID")
);
ALTER TABLE "beauty_mst_location" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_location" FOR ALL USING (true) WITH CHECK (true);


-- FACT_MONTHLY_SALES → beauty_fact_monthly_sales
DROP TABLE IF EXISTS "beauty_fact_monthly_sales" CASCADE;
CREATE TABLE "beauty_fact_monthly_sales" (
  "SALE_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "CHANNEL_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "SALES_QTY" BIGINT,
  "SALES_AMOUNT" DOUBLE PRECISION,
  "CURRENCY" TEXT,
  "RETURN_QTY" BIGINT,
  "NET_SALES_QTY" BIGINT
  , PRIMARY KEY ("SALE_ID", "PRODUCT_ID", "CHANNEL_ID")
);
ALTER TABLE "beauty_fact_monthly_sales" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_fact_monthly_sales" FOR ALL USING (true) WITH CHECK (true);


-- FACT_INVENTORY → beauty_fact_inventory
DROP TABLE IF EXISTS "beauty_fact_inventory" CASCADE;
CREATE TABLE "beauty_fact_inventory" (
  "INVENTORY_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "LOCATION_ID" TEXT,
  "SNAPSHOT_DATE" TEXT,
  "STOCK_QTY" BIGINT,
  "SAFETY_STOCK_QTY" BIGINT,
  "REORDER_POINT" BIGINT,
  "COVERAGE_WEEKS" DOUBLE PRECISION,
  "STOCK_STATUS" TEXT
  , PRIMARY KEY ("INVENTORY_ID", "PRODUCT_ID", "LOCATION_ID")
);
ALTER TABLE "beauty_fact_inventory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_fact_inventory" FOR ALL USING (true) WITH CHECK (true);


-- MST_OFFICE → beauty_mst_office
DROP TABLE IF EXISTS "beauty_mst_office" CASCADE;
CREATE TABLE "beauty_mst_office" (
  "OFFICE_CD" TEXT,
  "OFFICE_NAME" TEXT,
  "REGION" TEXT,
  "OFFICE_TYPE" TEXT,
  "LT" BIGINT,
  "T" BIGINT,
  "SS_PARAM" DOUBLE PRECISION,
  "CURRENCY" TEXT,
  "TIMEZONE" TEXT
  , PRIMARY KEY ("OFFICE_CD")
);
ALTER TABLE "beauty_mst_office" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_office" FOR ALL USING (true) WITH CHECK (true);


-- MST_PART → beauty_mst_part
DROP TABLE IF EXISTS "beauty_mst_part" CASCADE;
CREATE TABLE "beauty_mst_part" (
  "PART_CD" TEXT,
  "PART_NAME" TEXT,
  "PART_TYPE" TEXT,
  "LINKED_PRODUCT_ID" TEXT,
  "UNIT" TEXT,
  "UNIT_COST_KRW" BIGINT,
  "STD_DEMAND_MONTHLY" BIGINT
  , PRIMARY KEY ("PART_CD")
);
ALTER TABLE "beauty_mst_part" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_part" FOR ALL USING (true) WITH CHECK (true);


-- MST_SUPPLY_ROUTE → beauty_mst_supply_route
DROP TABLE IF EXISTS "beauty_mst_supply_route" CASCADE;
CREATE TABLE "beauty_mst_supply_route" (
  "ROUTE_ID" TEXT,
  "SUPPLIER_ID" TEXT,
  "OFFICE_CD" TEXT,
  "TRANSPORT_MODE" TEXT,
  "ROUTE_LT_DAYS" BIGINT,
  "FREIGHT_COST_KRW" BIGINT,
  "RELIABILITY_PCT" BIGINT
  , PRIMARY KEY ("ROUTE_ID")
);
ALTER TABLE "beauty_mst_supply_route" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_mst_supply_route" FOR ALL USING (true) WITH CHECK (true);


-- FACT_REPLENISHMENT_ORDER → beauty_fact_replenishment_order
DROP TABLE IF EXISTS "beauty_fact_replenishment_order" CASCADE;
CREATE TABLE "beauty_fact_replenishment_order" (
  "ORDER_ID" TEXT,
  "OFFICE_CD" TEXT,
  "PART_CD" TEXT,
  "ORDER_YM" TEXT,
  "ORDER_DT" TEXT,
  "PROMISED_DT" TEXT,
  "ACTUAL_DT" TEXT,
  "ORDER_QTY" BIGINT,
  "RECEIVED_QTY" BIGINT,
  "UNIT_COST" BIGINT,
  "CURRENCY" TEXT,
  "ORDER_AMOUNT" DOUBLE PRECISION,
  "DELAY_DAYS" BIGINT,
  "STATUS" TEXT
  , PRIMARY KEY ("ORDER_ID", "OFFICE_CD", "PART_CD")
);
ALTER TABLE "beauty_fact_replenishment_order" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_fact_replenishment_order" FOR ALL USING (true) WITH CHECK (true);


-- FACT_STOCKOUT_EVENT → beauty_fact_stockout_event
DROP TABLE IF EXISTS "beauty_fact_stockout_event" CASCADE;
CREATE TABLE "beauty_fact_stockout_event" (
  "STOCKOUT_ID" TEXT,
  "OFFICE_CD" TEXT,
  "PART_CD" TEXT,
  "STOCKOUT_YM" TEXT,
  "START_DT" TEXT,
  "END_DT" TEXT,
  "DURATION_DAYS" BIGINT,
  "LOST_SALES_QTY" BIGINT,
  "CAUSE_CODE" TEXT,
  "LINKED_ORDER_ID" TEXT
  , PRIMARY KEY ("STOCKOUT_ID", "OFFICE_CD", "PART_CD")
);
ALTER TABLE "beauty_fact_stockout_event" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "beauty_fact_stockout_event" FOR ALL USING (true) WITH CHECK (true);


-- ===== SUPPLY =====

-- MST_PART → supply_mst_part
DROP TABLE IF EXISTS "supply_mst_part" CASCADE;
CREATE TABLE "supply_mst_part" (
  "PART_ID" TEXT,
  "PART_NAME" TEXT,
  "PART_CLASS" TEXT,
  "PART_TYPE" TEXT,
  "DEMAND_TYPE" TEXT,
  "CATEGORY" TEXT,
  "UNIT_COST_KRW" BIGINT,
  "STD_MONTHLY_DEMAND" BIGINT,
  "LEAD_TIME_DAYS" TEXT,
  "MOQ" BIGINT,
  "SUPPLIER_ID" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("PART_ID")
);
ALTER TABLE "supply_mst_part" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "supply_mst_part" FOR ALL USING (true) WITH CHECK (true);


-- MST_SUPPLIER → supply_mst_supplier
DROP TABLE IF EXISTS "supply_mst_supplier" CASCADE;
CREATE TABLE "supply_mst_supplier" (
  "SUPPLIER_ID" TEXT,
  "SUPPLIER_NAME" TEXT,
  "SUPPLIER_TYPE" TEXT,
  "COUNTRY" TEXT,
  "LEAD_TIME_DAYS" TEXT,
  "MOQ" BIGINT,
  "RELIABILITY_PCT" BIGINT,
  "PAYMENT_TERMS" TEXT
  , PRIMARY KEY ("SUPPLIER_ID")
);
ALTER TABLE "supply_mst_supplier" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "supply_mst_supplier" FOR ALL USING (true) WITH CHECK (true);


-- MST_WAREHOUSE → supply_mst_warehouse
DROP TABLE IF EXISTS "supply_mst_warehouse" CASCADE;
CREATE TABLE "supply_mst_warehouse" (
  "WAREHOUSE_ID" TEXT,
  "WAREHOUSE_NAME" TEXT,
  "WAREHOUSE_TYPE" TEXT,
  "REGION" TEXT,
  "CAPACITY_UNITS" BIGINT,
  "MANAGER_NAME" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("WAREHOUSE_ID")
);
ALTER TABLE "supply_mst_warehouse" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "supply_mst_warehouse" FOR ALL USING (true) WITH CHECK (true);


-- FACT_MONTHLY_DEMAND → supply_fact_monthly_demand
DROP TABLE IF EXISTS "supply_fact_monthly_demand" CASCADE;
CREATE TABLE "supply_fact_monthly_demand" (
  "DEMAND_ID" TEXT,
  "PART_ID" TEXT,
  "WAREHOUSE_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "DEMAND_TYPE_ACTUAL" TEXT,
  "DEMAND_QTY" BIGINT,
  "FORECAST_QTY" DOUBLE PRECISION,
  "FORECAST_ERROR_PCT" DOUBLE PRECISION,
  "UNIT_COST_KRW" BIGINT,
  "DEMAND_AMOUNT_KRW" BIGINT
  , PRIMARY KEY ("DEMAND_ID", "PART_ID", "WAREHOUSE_ID")
);
ALTER TABLE "supply_fact_monthly_demand" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "supply_fact_monthly_demand" FOR ALL USING (true) WITH CHECK (true);


-- FACT_INVENTORY → supply_fact_inventory
DROP TABLE IF EXISTS "supply_fact_inventory" CASCADE;
CREATE TABLE "supply_fact_inventory" (
  "INVENTORY_ID" TEXT,
  "PART_ID" TEXT,
  "WAREHOUSE_ID" TEXT,
  "SNAPSHOT_DATE" TEXT,
  "STOCK_QTY" BIGINT,
  "SAFETY_STOCK_QTY" BIGINT,
  "REORDER_POINT" BIGINT,
  "STOCK_STATUS" TEXT,
  "INVENTORY_VALUE_KRW" BIGINT,
  "LAST_MOVEMENT_DATE" TEXT
  , PRIMARY KEY ("INVENTORY_ID", "PART_ID", "WAREHOUSE_ID")
);
ALTER TABLE "supply_fact_inventory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "supply_fact_inventory" FOR ALL USING (true) WITH CHECK (true);


-- FACT_ORDER → supply_fact_order
DROP TABLE IF EXISTS "supply_fact_order" CASCADE;
CREATE TABLE "supply_fact_order" (
  "ORDER_ID" TEXT,
  "PART_ID" TEXT,
  "SUPPLIER_ID" TEXT,
  "WAREHOUSE_ID" TEXT,
  "ORDER_DATE" TEXT,
  "PROMISED_DATE" TEXT,
  "ACTUAL_DATE" TEXT,
  "ORDER_QTY" BIGINT,
  "RECEIVED_QTY" BIGINT,
  "UNIT_COST_KRW" BIGINT,
  "ORDER_AMOUNT_KRW" BIGINT,
  "DELAY_DAYS" BIGINT,
  "ORDER_TYPE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("ORDER_ID", "PART_ID", "SUPPLIER_ID")
);
ALTER TABLE "supply_fact_order" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "supply_fact_order" FOR ALL USING (true) WITH CHECK (true);


-- ===== ENERGY =====

-- MST_REGION → energy_mst_region
DROP TABLE IF EXISTS "energy_mst_region" CASCADE;
CREATE TABLE "energy_mst_region" (
  "REGION_ID" TEXT,
  "REGION_NAME" TEXT,
  "REGION_TYPE" TEXT,
  "POPULATION_MILLION" DOUBLE PRECISION,
  "PEAK_DEMAND_MW" TEXT,
  "GRID_ZONE" TEXT
  , PRIMARY KEY ("REGION_ID")
);
ALTER TABLE "energy_mst_region" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "energy_mst_region" FOR ALL USING (true) WITH CHECK (true);


-- MST_PLANT → energy_mst_plant
DROP TABLE IF EXISTS "energy_mst_plant" CASCADE;
CREATE TABLE "energy_mst_plant" (
  "PLANT_ID" TEXT,
  "PLANT_NAME" TEXT,
  "PLANT_TYPE" TEXT,
  "REGION_ID" TEXT,
  "CAPACITY_MW" BIGINT,
  "COMMISSION_DATE" TEXT,
  "STATUS" TEXT,
  "FUEL_TYPE" TEXT,
  "OPERATOR_NAME" TEXT,
  "CO2_EMISSION_FACTOR" DOUBLE PRECISION
  , PRIMARY KEY ("PLANT_ID")
);
ALTER TABLE "energy_mst_plant" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "energy_mst_plant" FOR ALL USING (true) WITH CHECK (true);


-- MST_METER → energy_mst_meter
DROP TABLE IF EXISTS "energy_mst_meter" CASCADE;
CREATE TABLE "energy_mst_meter" (
  "METER_ID" TEXT,
  "METER_NAME" TEXT,
  "METER_TYPE" TEXT,
  "REGION_ID" TEXT,
  "CUSTOMER_TYPE" TEXT,
  "CONTRACT_CAPACITY_KW" BIGINT,
  "VOLTAGE_LEVEL" TEXT,
  "INSTALL_DATE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("METER_ID")
);
ALTER TABLE "energy_mst_meter" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "energy_mst_meter" FOR ALL USING (true) WITH CHECK (true);


-- FACT_DAILY_USAGE → energy_fact_daily_usage
DROP TABLE IF EXISTS "energy_fact_daily_usage" CASCADE;
CREATE TABLE "energy_fact_daily_usage" (
  "USAGE_ID" TEXT,
  "METER_ID" TEXT,
  "USAGE_DATE" TEXT,
  "USAGE_KWH" DOUBLE PRECISION,
  "PEAK_KW" TEXT,
  "OFFPEAK_KW" TEXT,
  "REACTIVE_KVARH" DOUBLE PRECISION,
  "POWER_FACTOR" DOUBLE PRECISION,
  "IS_PEAK_DAY" TEXT,
  "ESTIMATED_FLAG" TEXT
  , PRIMARY KEY ("USAGE_ID", "METER_ID", "USAGE_DATE")
);
ALTER TABLE "energy_fact_daily_usage" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "energy_fact_daily_usage" FOR ALL USING (true) WITH CHECK (true);


-- FACT_MONTHLY_BILL → energy_fact_monthly_bill
DROP TABLE IF EXISTS "energy_fact_monthly_bill" CASCADE;
CREATE TABLE "energy_fact_monthly_bill" (
  "BILL_ID" TEXT,
  "METER_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "USAGE_KWH" DOUBLE PRECISION,
  "PEAK_USAGE_KWH" TEXT,
  "OFFPEAK_USAGE_KWH" TEXT,
  "DEMAND_CHARGE_KRW" BIGINT,
  "ENERGY_CHARGE_KRW" DOUBLE PRECISION,
  "FUEL_ADJUSTMENT_KRW" DOUBLE PRECISION,
  "TAX_KRW" DOUBLE PRECISION,
  "TOTAL_BILL_KRW" DOUBLE PRECISION,
  "PAYMENT_DATE" TEXT,
  "PAYMENT_STATUS" TEXT
  , PRIMARY KEY ("BILL_ID", "METER_ID", "YEAR_MONTH")
);
ALTER TABLE "energy_fact_monthly_bill" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "energy_fact_monthly_bill" FOR ALL USING (true) WITH CHECK (true);


-- FACT_OUTAGE → energy_fact_outage
DROP TABLE IF EXISTS "energy_fact_outage" CASCADE;
CREATE TABLE "energy_fact_outage" (
  "OUTAGE_ID" TEXT,
  "PLANT_ID" TEXT,
  "REGION_ID" TEXT,
  "OUTAGE_DATE" TEXT,
  "START_TIME" TEXT,
  "END_TIME" TEXT,
  "DURATION_HOURS" DOUBLE PRECISION,
  "OUTAGE_TYPE" TEXT,
  "AFFECTED_CUSTOMERS" BIGINT,
  "ENERGY_NOT_SUPPLIED_MWH" TEXT,
  "CAUSE_DESCRIPTION" TEXT,
  "RESTORATION_METHOD" TEXT,
  "COST_KRW" DOUBLE PRECISION
  , PRIMARY KEY ("OUTAGE_ID", "PLANT_ID", "REGION_ID")
);
ALTER TABLE "energy_fact_outage" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "energy_fact_outage" FOR ALL USING (true) WITH CHECK (true);


-- ===== MANUFACTURING =====

-- MST_LINE → manufacturing_mst_line
DROP TABLE IF EXISTS "manufacturing_mst_line" CASCADE;
CREATE TABLE "manufacturing_mst_line" (
  "LINE_ID" TEXT,
  "LINE_NAME" TEXT,
  "LINE_TYPE" TEXT,
  "FACTORY_FLOOR" TEXT,
  "SHIFT_COUNT" BIGINT,
  "DESIGN_CAPACITY_DAILY" BIGINT,
  "STATUS" TEXT,
  "LINE_MANAGER" TEXT
  , PRIMARY KEY ("LINE_ID")
);
ALTER TABLE "manufacturing_mst_line" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "manufacturing_mst_line" FOR ALL USING (true) WITH CHECK (true);


-- MST_EQUIPMENT → manufacturing_mst_equipment
DROP TABLE IF EXISTS "manufacturing_mst_equipment" CASCADE;
CREATE TABLE "manufacturing_mst_equipment" (
  "EQUIPMENT_ID" TEXT,
  "EQUIPMENT_NAME" TEXT,
  "EQUIPMENT_TYPE" TEXT,
  "LINE_ID" TEXT,
  "MANUFACTURER" TEXT,
  "INSTALL_DATE" TEXT,
  "DESIGN_CAPACITY_PER_HOUR" BIGINT,
  "OEE_TARGET_PCT" BIGINT,
  "MAINTENANCE_CYCLE_DAYS" BIGINT,
  "STATUS" TEXT,
  "ASSET_VALUE_KRW" BIGINT
  , PRIMARY KEY ("EQUIPMENT_ID", "LINE_ID", "INSTALL_DATE")
);
ALTER TABLE "manufacturing_mst_equipment" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "manufacturing_mst_equipment" FOR ALL USING (true) WITH CHECK (true);


-- MST_PRODUCT → manufacturing_mst_product
DROP TABLE IF EXISTS "manufacturing_mst_product" CASCADE;
CREATE TABLE "manufacturing_mst_product" (
  "PRODUCT_ID" TEXT,
  "PRODUCT_NAME" TEXT,
  "PRODUCT_TYPE" TEXT,
  "CATEGORY" TEXT,
  "LINE_ID" TEXT,
  "CYCLE_TIME_SECONDS" TEXT,
  "STANDARD_COST_KRW" BIGINT,
  "DEMAND_TYPE" TEXT,
  "TARGET_DAILY_OUTPUT" BIGINT,
  "DEFECT_THRESHOLD_PCT" DOUBLE PRECISION,
  "LAUNCH_DATE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("PRODUCT_ID", "LINE_ID", "LAUNCH_DATE")
);
ALTER TABLE "manufacturing_mst_product" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "manufacturing_mst_product" FOR ALL USING (true) WITH CHECK (true);


-- FACT_PRODUCTION → manufacturing_fact_production
DROP TABLE IF EXISTS "manufacturing_fact_production" CASCADE;
CREATE TABLE "manufacturing_fact_production" (
  "PRODUCTION_ID" TEXT,
  "LINE_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "PRODUCTION_DATE" TEXT,
  "SHIFT" TEXT,
  "PLANNED_OUTPUT" BIGINT,
  "ACTUAL_OUTPUT" BIGINT,
  "UTILIZATION_RATE_PCT" DOUBLE PRECISION,
  "OPERATION_HOURS" DOUBLE PRECISION,
  "DOWNTIME_HOURS" TEXT,
  "DOWNTIME_REASON" TEXT,
  "YIELD_RATE_PCT" DOUBLE PRECISION
  , PRIMARY KEY ("PRODUCTION_ID", "LINE_ID", "PRODUCT_ID")
);
ALTER TABLE "manufacturing_fact_production" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "manufacturing_fact_production" FOR ALL USING (true) WITH CHECK (true);


-- FACT_DEFECT → manufacturing_fact_defect
DROP TABLE IF EXISTS "manufacturing_fact_defect" CASCADE;
CREATE TABLE "manufacturing_fact_defect" (
  "DEFECT_ID" TEXT,
  "LINE_ID" TEXT,
  "EQUIPMENT_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "DEFECT_DATE" TEXT,
  "DEFECT_TYPE" TEXT,
  "INSPECTED_QTY" BIGINT,
  "DEFECT_QTY" BIGINT,
  "DEFECT_RATE_PCT" DOUBLE PRECISION,
  "SEVERITY" TEXT,
  "DISPOSITION" TEXT,
  "REWORK_COST_KRW" DOUBLE PRECISION,
  "ROOT_CAUSE" TEXT
  , PRIMARY KEY ("DEFECT_ID", "LINE_ID", "EQUIPMENT_ID")
);
ALTER TABLE "manufacturing_fact_defect" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "manufacturing_fact_defect" FOR ALL USING (true) WITH CHECK (true);


-- FACT_MAINTENANCE → manufacturing_fact_maintenance
DROP TABLE IF EXISTS "manufacturing_fact_maintenance" CASCADE;
CREATE TABLE "manufacturing_fact_maintenance" (
  "MAINTENANCE_ID" TEXT,
  "EQUIPMENT_ID" TEXT,
  "MAINTENANCE_DATE" TEXT,
  "MAINTENANCE_TYPE" TEXT,
  "STATUS" TEXT,
  "PLANNED_HOURS" DOUBLE PRECISION,
  "ACTUAL_HOURS" DOUBLE PRECISION,
  "TECHNICIAN_ID" TEXT,
  "PARTS_COST_KRW" DOUBLE PRECISION,
  "LABOR_COST_KRW" DOUBLE PRECISION,
  "TOTAL_COST_KRW" DOUBLE PRECISION,
  "NEXT_MAINTENANCE_DATE" TEXT,
  "DOWNTIME_HOURS" TEXT,
  "RESULT_NOTE" TEXT
  , PRIMARY KEY ("MAINTENANCE_ID", "EQUIPMENT_ID", "MAINTENANCE_DATE")
);
ALTER TABLE "manufacturing_fact_maintenance" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "manufacturing_fact_maintenance" FOR ALL USING (true) WITH CHECK (true);


-- ===== LOGISTICS =====

-- MST_HUB → logistics_mst_hub
DROP TABLE IF EXISTS "logistics_mst_hub" CASCADE;
CREATE TABLE "logistics_mst_hub" (
  "HUB_ID" TEXT,
  "HUB_NAME" TEXT,
  "HUB_TYPE" TEXT,
  "REGION" TEXT,
  "ADDRESS" TEXT,
  "CAPACITY_PACKAGES_DAILY" BIGINT,
  "DOCK_COUNT" BIGINT,
  "OPERATING_HOURS" TEXT,
  "MANAGER_NAME" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("HUB_ID")
);
ALTER TABLE "logistics_mst_hub" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "logistics_mst_hub" FOR ALL USING (true) WITH CHECK (true);


-- MST_VEHICLE → logistics_mst_vehicle
DROP TABLE IF EXISTS "logistics_mst_vehicle" CASCADE;
CREATE TABLE "logistics_mst_vehicle" (
  "VEHICLE_ID" TEXT,
  "VEHICLE_NAME" TEXT,
  "VEHICLE_TYPE" TEXT,
  "LICENSE_PLATE" TEXT,
  "HUB_ID" TEXT,
  "CAPACITY_KG" BIGINT,
  "CAPACITY_VOLUME_M3" DOUBLE PRECISION,
  "FUEL_TYPE" TEXT,
  "FUEL_EFFICIENCY_KM_PER_L" DOUBLE PRECISION,
  "DRIVER_NAME" TEXT,
  "STATUS" TEXT,
  "PURCHASE_DATE" TEXT,
  "MILEAGE_KM" BIGINT
  , PRIMARY KEY ("VEHICLE_ID")
);
ALTER TABLE "logistics_mst_vehicle" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "logistics_mst_vehicle" FOR ALL USING (true) WITH CHECK (true);


-- MST_ROUTE → logistics_mst_route
DROP TABLE IF EXISTS "logistics_mst_route" CASCADE;
CREATE TABLE "logistics_mst_route" (
  "ROUTE_ID" TEXT,
  "ROUTE_NAME" TEXT,
  "ORIGIN_HUB_ID" TEXT,
  "DEST_HUB_ID" TEXT,
  "DISTANCE_KM" BIGINT,
  "STANDARD_TIME_HOURS" TEXT,
  "ROUTE_TYPE" TEXT,
  "TOLL_KRW" BIGINT,
  "VEHICLE_TYPE_REQUIRED" TEXT,
  "FREQUENCY" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("ROUTE_ID")
);
ALTER TABLE "logistics_mst_route" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "logistics_mst_route" FOR ALL USING (true) WITH CHECK (true);


-- FACT_DELIVERY → logistics_fact_delivery
DROP TABLE IF EXISTS "logistics_fact_delivery" CASCADE;
CREATE TABLE "logistics_fact_delivery" (
  "DELIVERY_ID" TEXT,
  "VEHICLE_ID" TEXT,
  "ROUTE_ID" TEXT,
  "HUB_ID" TEXT,
  "DELIVERY_DATE" TEXT,
  "DEPARTURE_TIME" TEXT,
  "ARRIVAL_TIME" TEXT,
  "PACKAGE_COUNT" BIGINT,
  "TOTAL_WEIGHT_KG" DOUBLE PRECISION,
  "TOTAL_VOLUME_M3" DOUBLE PRECISION,
  "DELIVERY_SUCCESS_COUNT" BIGINT,
  "DELIVERY_FAIL_COUNT" BIGINT,
  "FAIL_REASON" TEXT,
  "DRIVER_NAME" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("DELIVERY_ID", "VEHICLE_ID", "ROUTE_ID")
);
ALTER TABLE "logistics_fact_delivery" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "logistics_fact_delivery" FOR ALL USING (true) WITH CHECK (true);


-- FACT_DELAY → logistics_fact_delay
DROP TABLE IF EXISTS "logistics_fact_delay" CASCADE;
CREATE TABLE "logistics_fact_delay" (
  "DELAY_ID" TEXT,
  "DELIVERY_ID" TEXT,
  "VEHICLE_ID" TEXT,
  "ROUTE_ID" TEXT,
  "DELAY_DATE" TEXT,
  "SCHEDULED_ARRIVAL" TEXT,
  "ACTUAL_ARRIVAL" TEXT,
  "DELAY_MINUTES" BIGINT,
  "DELAY_CAUSE" TEXT,
  "SEVERITY" TEXT,
  "CUSTOMER_COMPLAINT" TEXT,
  "COMPENSATION_KRW" DOUBLE PRECISION,
  "RESOLUTION_STATUS" TEXT
  , PRIMARY KEY ("DELAY_ID", "DELIVERY_ID", "VEHICLE_ID")
);
ALTER TABLE "logistics_fact_delay" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "logistics_fact_delay" FOR ALL USING (true) WITH CHECK (true);


-- FACT_COST → logistics_fact_cost
DROP TABLE IF EXISTS "logistics_fact_cost" CASCADE;
CREATE TABLE "logistics_fact_cost" (
  "COST_ID" TEXT,
  "VEHICLE_ID" TEXT,
  "ROUTE_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "FUEL_COST_KRW" BIGINT,
  "TOLL_COST_KRW" BIGINT,
  "MAINTENANCE_COST_KRW" DOUBLE PRECISION,
  "DRIVER_WAGE_KRW" BIGINT,
  "INSURANCE_KRW" BIGINT,
  "DEPRECIATION_KRW" BIGINT,
  "OTHER_COST_KRW" DOUBLE PRECISION,
  "TOTAL_COST_KRW" BIGINT,
  "REVENUE_KRW" BIGINT,
  "PROFIT_KRW" BIGINT,
  "COST_PER_KM_KRW" DOUBLE PRECISION
  , PRIMARY KEY ("COST_ID", "VEHICLE_ID", "ROUTE_ID")
);
ALTER TABLE "logistics_fact_cost" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "logistics_fact_cost" FOR ALL USING (true) WITH CHECK (true);


-- ===== FINANCE =====

-- MST_PRODUCT → finance_mst_product
DROP TABLE IF EXISTS "finance_mst_product" CASCADE;
CREATE TABLE "finance_mst_product" (
  "PRODUCT_ID" TEXT,
  "PRODUCT_NAME" TEXT,
  "PRODUCT_TYPE" TEXT,
  "CATEGORY" TEXT,
  "INTEREST_RATE_PCT" DOUBLE PRECISION,
  "MIN_AMOUNT_KRW" DOUBLE PRECISION,
  "MAX_AMOUNT_KRW" DOUBLE PRECISION,
  "TERM_MONTHS" DOUBLE PRECISION,
  "RISK_GRADE" TEXT,
  "STATUS" TEXT,
  "LAUNCH_DATE" TEXT,
  "REGULATOR" TEXT
  , PRIMARY KEY ("PRODUCT_ID")
);
ALTER TABLE "finance_mst_product" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "finance_mst_product" FOR ALL USING (true) WITH CHECK (true);


-- MST_CUSTOMER → finance_mst_customer
DROP TABLE IF EXISTS "finance_mst_customer" CASCADE;
CREATE TABLE "finance_mst_customer" (
  "CUSTOMER_ID" TEXT,
  "CUSTOMER_TYPE" TEXT,
  "CUSTOMER_GRADE" TEXT,
  "AGE_GROUP" TEXT,
  "REGION" TEXT,
  "CREDIT_SCORE" DOUBLE PRECISION,
  "TOTAL_ASSETS_MILLION_KRW" DOUBLE PRECISION,
  "RELATIONSHIP_MONTHS" BIGINT,
  "RISK_APPETITE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("CUSTOMER_ID")
);
ALTER TABLE "finance_mst_customer" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "finance_mst_customer" FOR ALL USING (true) WITH CHECK (true);


-- MST_BRANCH → finance_mst_branch
DROP TABLE IF EXISTS "finance_mst_branch" CASCADE;
CREATE TABLE "finance_mst_branch" (
  "BRANCH_ID" TEXT,
  "BRANCH_NAME" TEXT,
  "BRANCH_TYPE" TEXT,
  "REGION" TEXT,
  "ADDRESS" TEXT,
  "MANAGER_NAME" TEXT,
  "OPEN_DATE" TEXT,
  "EMPLOYEE_COUNT" BIGINT,
  "STATUS" TEXT
  , PRIMARY KEY ("BRANCH_ID")
);
ALTER TABLE "finance_mst_branch" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "finance_mst_branch" FOR ALL USING (true) WITH CHECK (true);


-- FACT_TRANSACTION → finance_fact_transaction
DROP TABLE IF EXISTS "finance_fact_transaction" CASCADE;
CREATE TABLE "finance_fact_transaction" (
  "TRANSACTION_ID" TEXT,
  "CUSTOMER_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "BRANCH_ID" TEXT,
  "TRANSACTION_DATE" TEXT,
  "TRANSACTION_TIME" TEXT,
  "TRANSACTION_TYPE" TEXT,
  "AMOUNT_KRW" BIGINT,
  "BALANCE_AFTER_KRW" DOUBLE PRECISION,
  "CHANNEL" TEXT,
  "CURRENCY" TEXT,
  "IS_ANOMALY" TEXT,
  "ANOMALY_TYPE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("TRANSACTION_ID", "CUSTOMER_ID", "PRODUCT_ID")
);
ALTER TABLE "finance_fact_transaction" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "finance_fact_transaction" FOR ALL USING (true) WITH CHECK (true);


-- FACT_RISK → finance_fact_risk
DROP TABLE IF EXISTS "finance_fact_risk" CASCADE;
CREATE TABLE "finance_fact_risk" (
  "RISK_ID" TEXT,
  "CUSTOMER_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "CREDIT_SCORE_CURRENT" BIGINT,
  "PD_PCT" DOUBLE PRECISION,
  "LGD_PCT" DOUBLE PRECISION,
  "EAD_KRW" BIGINT,
  "EXPECTED_LOSS_KRW" BIGINT,
  "RISK_GRADE" TEXT,
  "RISK_GRADE_PREV" TEXT,
  "GRADE_CHANGE" TEXT,
  "COLLATERAL_VALUE_KRW" DOUBLE PRECISION,
  "MARKET_RISK_VAR_KRW" DOUBLE PRECISION,
  "LIQUIDITY_RISK_SCORE" BIGINT
  , PRIMARY KEY ("RISK_ID", "CUSTOMER_ID", "YEAR_MONTH")
);
ALTER TABLE "finance_fact_risk" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "finance_fact_risk" FOR ALL USING (true) WITH CHECK (true);


-- FACT_PERFORMANCE → finance_fact_performance
DROP TABLE IF EXISTS "finance_fact_performance" CASCADE;
CREATE TABLE "finance_fact_performance" (
  "PERF_ID" TEXT,
  "BRANCH_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "NEW_CUSTOMER_COUNT" BIGINT,
  "CLOSED_CUSTOMER_COUNT" BIGINT,
  "TOTAL_DEPOSIT_KRW" BIGINT,
  "TOTAL_LOAN_KRW" BIGINT,
  "TOTAL_INVESTMENT_KRW" BIGINT,
  "NET_INTEREST_INCOME_KRW" BIGINT,
  "FEE_INCOME_KRW" BIGINT,
  "TOTAL_REVENUE_KRW" BIGINT,
  "OPERATING_COST_KRW" BIGINT,
  "NET_PROFIT_KRW" BIGINT,
  "NPS_SCORE" DOUBLE PRECISION,
  "COMPLAINT_COUNT" BIGINT,
  "LOAN_DEFAULT_COUNT" DOUBLE PRECISION
  , PRIMARY KEY ("PERF_ID", "BRANCH_ID", "YEAR_MONTH")
);
ALTER TABLE "finance_fact_performance" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON "finance_fact_performance" FOR ALL USING (true) WITH CHECK (true);

