-- Supabase SQL Editor: DROP + CREATE (uppercase columns)
-- =========================================================

-- DATA_DICTIONARY.csv
DROP TABLE IF EXISTS data_dictionary CASCADE;
CREATE TABLE data_dictionary (
  "TABLE_NAME" TEXT,
  "COLUMN_NAME" TEXT,
  "COLUMN_NAME_KO" TEXT,
  "DATA_TYPE" TEXT,
  "NULLABLE" TEXT,
  "IS_PK" TEXT,
  "IS_FK" TEXT,
  "FK_REF" TEXT,
  "DESCRIPTION" TEXT
  , PRIMARY KEY ("TABLE_NAME")
);

ALTER TABLE data_dictionary ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON data_dictionary
  FOR ALL USING (true) WITH CHECK (true);


-- FACT_INVENTORY.csv
DROP TABLE IF EXISTS fact_inventory CASCADE;
CREATE TABLE fact_inventory (
  "INVENTORY_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "LOCATION_ID" TEXT,
  "SNAPSHOT_DATE" TEXT,
  "STOCK_QTY" BIGINT,
  "SAFETY_STOCK_QTY" BIGINT,
  "REORDER_POINT" BIGINT,
  "COVERAGE_WEEKS" DOUBLE PRECISION,
  "STOCK_STATUS" TEXT
  , PRIMARY KEY ("INVENTORY_ID", "PRODUCT_ID", "LOCATION_ID")
);

ALTER TABLE fact_inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON fact_inventory
  FOR ALL USING (true) WITH CHECK (true);


-- FACT_INVENTORY_SNAPSHOT.csv
DROP TABLE IF EXISTS fact_inventory_snapshot CASCADE;
CREATE TABLE fact_inventory_snapshot (
  "SNAPSHOT_ID" TEXT,
  "SNAPSHOT_DATE" TEXT,
  "PRODUCT_NO" TEXT,
  "SUPPLIER_CD" TEXT,
  "WAREHOUSE_CD" TEXT,
  "STOCK_QTY" BIGINT,
  "SAFETY_STOCK_QTY" BIGINT,
  "REORDER_POINT" BIGINT,
  "UNIT_COST" BIGINT,
  "STATUS" TEXT
  , PRIMARY KEY ("SNAPSHOT_ID", "SNAPSHOT_DATE", "SUPPLIER_CD")
);

ALTER TABLE fact_inventory_snapshot ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON fact_inventory_snapshot
  FOR ALL USING (true) WITH CHECK (true);


-- FACT_MONTHLY_DEMAND.csv
DROP TABLE IF EXISTS fact_monthly_demand CASCADE;
CREATE TABLE fact_monthly_demand (
  "DEMAND_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "PRODUCT_NO" TEXT,
  "WAREHOUSE_CD" TEXT,
  "DEMAND_QTY" BIGINT,
  "SALES_AMT" BIGINT,
  "RETURN_QTY" BIGINT
  , PRIMARY KEY ("DEMAND_ID", "YEAR_MONTH", "WAREHOUSE_CD")
);

ALTER TABLE fact_monthly_demand ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON fact_monthly_demand
  FOR ALL USING (true) WITH CHECK (true);


-- FACT_MONTHLY_SALES.csv
DROP TABLE IF EXISTS fact_monthly_sales CASCADE;
CREATE TABLE fact_monthly_sales (
  "SALE_ID" TEXT,
  "PRODUCT_ID" TEXT,
  "CHANNEL_ID" TEXT,
  "YEAR_MONTH" TEXT,
  "SALES_QTY" BIGINT,
  "SALES_AMOUNT" DOUBLE PRECISION,
  "CURRENCY" TEXT,
  "RETURN_QTY" BIGINT,
  "NET_SALES_QTY" BIGINT
  , PRIMARY KEY ("SALE_ID", "PRODUCT_ID", "CHANNEL_ID")
);

ALTER TABLE fact_monthly_sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON fact_monthly_sales
  FOR ALL USING (true) WITH CHECK (true);


-- FACT_REPLENISHMENT_ORDER.csv
DROP TABLE IF EXISTS fact_replenishment_order CASCADE;
CREATE TABLE fact_replenishment_order (
  "ORDER_ID" TEXT,
  "OFFICE_CD" TEXT,
  "PART_CD" TEXT,
  "ORDER_YM" TEXT,
  "ORDER_DT" TEXT,
  "PROMISED_DT" TEXT,
  "ACTUAL_DT" TEXT,
  "ORDER_QTY" BIGINT,
  "RECEIVED_QTY" BIGINT,
  "UNIT_COST" BIGINT,
  "CURRENCY" TEXT,
  "ORDER_AMOUNT" DOUBLE PRECISION,
  "DELAY_DAYS" BIGINT,
  "STATUS" TEXT
  , PRIMARY KEY ("ORDER_ID", "OFFICE_CD", "PART_CD")
);

ALTER TABLE fact_replenishment_order ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON fact_replenishment_order
  FOR ALL USING (true) WITH CHECK (true);


-- FACT_STOCKOUT_EVENT.csv
DROP TABLE IF EXISTS fact_stockout_event CASCADE;
CREATE TABLE fact_stockout_event (
  "STOCKOUT_ID" TEXT,
  "OFFICE_CD" TEXT,
  "PART_CD" TEXT,
  "STOCKOUT_YM" TEXT,
  "START_DT" TEXT,
  "END_DT" TEXT,
  "DURATION_DAYS" BIGINT,
  "LOST_SALES_QTY" BIGINT,
  "CAUSE_CODE" TEXT,
  "LINKED_ORDER_ID" TEXT
  , PRIMARY KEY ("STOCKOUT_ID", "OFFICE_CD", "PART_CD")
);

ALTER TABLE fact_stockout_event ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON fact_stockout_event
  FOR ALL USING (true) WITH CHECK (true);


-- MST_CHANNEL.csv
DROP TABLE IF EXISTS mst_channel CASCADE;
CREATE TABLE mst_channel (
  "CHANNEL_ID" TEXT,
  "CHANNEL_NAME" TEXT,
  "CHANNEL_TYPE" TEXT,
  "REGION" TEXT,
  "CURRENCY" TEXT,
  "PLATFORM_FEE_PCT" BIGINT,
  "LOCATION" TEXT
  , PRIMARY KEY ("CHANNEL_ID")
);

ALTER TABLE mst_channel ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_channel
  FOR ALL USING (true) WITH CHECK (true);


-- MST_LOCATION.csv
DROP TABLE IF EXISTS mst_location CASCADE;
CREATE TABLE mst_location (
  "LOCATION_ID" TEXT,
  "LOCATION_NAME" TEXT,
  "LOCATION_TYPE" TEXT,
  "REGION" TEXT
  , PRIMARY KEY ("LOCATION_ID")
);

ALTER TABLE mst_location ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_location
  FOR ALL USING (true) WITH CHECK (true);


-- MST_OFFICE.csv
DROP TABLE IF EXISTS mst_office CASCADE;
CREATE TABLE mst_office (
  "OFFICE_CD" TEXT,
  "OFFICE_NAME" TEXT,
  "REGION" TEXT,
  "OFFICE_TYPE" TEXT,
  "LT" BIGINT,
  "T" BIGINT,
  "SS_PARAM" DOUBLE PRECISION,
  "CURRENCY" TEXT,
  "TIMEZONE" TEXT
  , PRIMARY KEY ("OFFICE_CD")
);

ALTER TABLE mst_office ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_office
  FOR ALL USING (true) WITH CHECK (true);


-- MST_PART.csv
DROP TABLE IF EXISTS mst_part CASCADE;
CREATE TABLE mst_part (
  "PART_CD" TEXT,
  "PART_NAME" TEXT,
  "PART_TYPE" TEXT,
  "LINKED_PRODUCT_ID" TEXT,
  "UNIT" TEXT,
  "UNIT_COST_KRW" BIGINT,
  "STD_DEMAND_MONTHLY" BIGINT
  , PRIMARY KEY ("PART_CD")
);

ALTER TABLE mst_part ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_part
  FOR ALL USING (true) WITH CHECK (true);


-- MST_PRODUCT.csv
DROP TABLE IF EXISTS mst_product CASCADE;
CREATE TABLE mst_product (
  "PRODUCT_ID" TEXT,
  "PRODUCT_NAME" TEXT,
  "CATEGORY" TEXT,
  "DEMAND_TYPE" TEXT,
  "SEASONAL_PEAK" TEXT,
  "LIFECYCLE_STAGE" TEXT,
  "SUPPLIER_ID" TEXT,
  "PRICE_KRW" BIGINT,
  "PRICE_USD" DOUBLE PRECISION,
  "LAUNCH_DATE" TEXT,
  "STATUS" TEXT
  , PRIMARY KEY ("PRODUCT_ID")
);

ALTER TABLE mst_product ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_product
  FOR ALL USING (true) WITH CHECK (true);


-- MST_SUPPLIER.csv
DROP TABLE IF EXISTS mst_supplier CASCADE;
CREATE TABLE mst_supplier (
  "SUPPLIER_ID" TEXT,
  "SUPPLIER_NAME" TEXT,
  "SUPPLIER_TYPE" TEXT,
  "COUNTRY" TEXT,
  "LEAD_TIME_DAYS" BIGINT,
  "MOQ" BIGINT,
  "PAYMENT_TERMS" TEXT
  , PRIMARY KEY ("SUPPLIER_ID")
);

ALTER TABLE mst_supplier ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_supplier
  FOR ALL USING (true) WITH CHECK (true);


-- MST_SUPPLY_ROUTE.csv
DROP TABLE IF EXISTS mst_supply_route CASCADE;
CREATE TABLE mst_supply_route (
  "ROUTE_ID" TEXT,
  "SUPPLIER_ID" TEXT,
  "OFFICE_CD" TEXT,
  "TRANSPORT_MODE" TEXT,
  "ROUTE_LT_DAYS" BIGINT,
  "FREIGHT_COST_KRW" BIGINT,
  "RELIABILITY_PCT" BIGINT
  , PRIMARY KEY ("ROUTE_ID")
);

ALTER TABLE mst_supply_route ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_supply_route
  FOR ALL USING (true) WITH CHECK (true);


-- MST_WAREHOUSE.csv
DROP TABLE IF EXISTS mst_warehouse CASCADE;
CREATE TABLE mst_warehouse (
  "WAREHOUSE_CD" TEXT,
  "WAREHOUSE_NAME" TEXT,
  "LOCATION" TEXT,
  "CAPACITY" BIGINT,
  "REGION" TEXT
  , PRIMARY KEY ("WAREHOUSE_CD")
);

ALTER TABLE mst_warehouse ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON mst_warehouse
  FOR ALL USING (true) WITH CHECK (true);

